---
- name: make `sudo` group passwordless
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
- name: disable root login with password via SSH
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin without-password" state=present
  notify: restart sshd
- name: disable password authentication via SSH
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart sshd
- name: adjust `sysctl` configuration
  copy: src=sysctl.conf dest=/etc/sysctl.conf owner=root group=root
- name: allow port 22
  ufw: rule=allow port=22 proto=tcp
- name: allow port 443
  ufw: rule=allow port=443 proto=tcp
- name: allow port 80
  ufw: rule=allow port=80 proto=tcp
- name: enable ufw
  ufw: state=enabled direction=incoming policy=deny
